### PR TITLE
Adding Glimcap 11

### PR DESCRIPTION
**Pull request by Heiwa1580**

### CODE REVIEW

**Comment by clone1018** [comment]
Looks like the file is named incorrectly `2021-04-22-2021-glimcap-part-11.md` instead of `2021-04-22-glimcap-part-eleven.md` 

Otherwise looks good to go!

**Comment by Heiwa1580** [comment]
@clone1018 I think I fixed it correctly?

**Comment by clone1018** [comment]
Looks like there's still an extra 2021 in it unfortunately.

**Comment by Heiwa1580** [comment]
Haha I didn't even notice that. I will fix that one

**Comment by Heiwa1580** [comment]
Ok I think I've officially fixed all the naming stuff

**Pull request merged**
